name: Trigger build

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger auth service backend build
      uses: passeidireto/trigger-external-workflow-action@main
      with:
        repository: ronin-code-io/auth-service-backend
        event: frontend-update
        github_pat: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
